### PR TITLE
Takes parameterized build parameters in to account when triggering a …

### PR DESCRIPTION
**Pull request by HexTank**
…job, if a keyvalue pair exists in the trigger email, it will try parsing that value with SimpleParameterValue.getValue(String), if this fails it will use the default value form the parameterized parameter.

Any keyvalue pair in the mail whose name exists as a parameterized parameter will be purged to avoid duplicate entries in the build parameter list.

### CODE REVIEW

**Comment by nickgrealy** [comment]
Sorry for the late reply. This change looks good! Any chance of a unit test as well, before I merge and publish a new release?

**Comment by HexTank** [comment]
I've never done any unit testing for Java/Jenkins/Grail, any pointers where I would start on such a thing?

**Comment by nickgrealy** [comment]
Sure, I'd start by looking at the existing tests (src/test/main), and see if you can use extend / build upon them. 

Let me know how you go.

**Comment by HexTank** [comment]
This looks alien to me, so it's going to take some time to get to grips with it, I'm assuming the main bits of interest are the things in StepDefs.groovy and adding something in to Runtime - Start Job.feature?

I'm unsure how I can run these tests locally though to know what I'm doing is correct, is there any online documentation to how this unit test script thing works?

**Comment by nickgrealy** [comment]
Ah ok... you've got four options.

If you're feeling adventurous, those `*.feature` files are called BDD (Behaviour Driven Development) tests (the `*.feature` files essentially are test templates (User Scenarios), written in the language "[Gherkin](https://cucumber.io/docs/reference)" and run by a framework called "[Cucumber](https://cucumber.io/)"). You can run them by running the [AcceptanceTests.java](https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/master/src/test/groovy/org/jenkinsci/plugins/pollmailboxtrigger/AcceptanceTests.java) class. It'll run all your feature files like standard Junit tests, and tell you what passes/fails.

If you're still feeling adventurous, but want something less "wordy", you could write a Jenkins integration test, which will start up a Jenkins instance, and let you interact with the web front end. An example is available [here](https://github.com/jenkinsci/groovy-events-listener-plugin/blob/master/src/test/groovy/org/jenkinsci/plugins/globalEventsPlugin/JenkinsTest.java), and the "guide" can be found [here](https://wiki.jenkins-ci.org/display/JENKINS/Unit+Test).

If you're not sure, I'd recommend starting with a simple Junit test (e.g. [MessagesWrapperTest.groovy](https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/master/src/test/groovy/org/jenkinsci/plugins/pollmailboxtrigger/mail/utils/MessagesWrapperTest.groovy)), and just trying to assert your expected behaviour. Using a mocking framework (e.g. [Mockito](http://mockito.org/)) might help you "Mock" some of the Jenkins objects.

If you're still stuck, don't sweat it. I'll take a look this weekend and try to write a test for your code. I'm just trying to exercise some (self) discipline and not commit code that breaks the plugin for other people (I've done it before!).

**Comment by HexTank** [comment]
Thanks for those links, really helpful.  Looks like I should go with the first method as a matter of course, and makes more sense for this test as a test for that code already exist in a roundabout way, this is just 'extra' functionality for existing code.

Not sure I'll have anything hooked up for the weekend, but I'll be playing with Gherkin either way.

**Comment by nickgrealy** [comment]
Fixes #11

**Pull request merged**
